In [2]:
import collections as cl
#module for processing container datatypes

In [3]:
#Counter() object is Dict with keyvalues & counts
#common methods: most_common, elements(), subtract()
c = cl.Counter('gallahad') 

In [4]:
c

Counter({'g': 1, 'a': 3, 'l': 2, 'h': 1, 'd': 1})

In [ ]:
c.keys()

In [79]:
c.items()

dict_items([('g', 1), ('a', 3), ('l', 2), ('h', 1), ('d', 1)])

In [61]:
c.most_common(1)

[('a', 3)]

In [64]:
sorted(c.elements())

['a', 'a', 'a', 'd', 'g', 'h', 'l', 'l']

In [13]:
#create lists through range()
num_list = list(range(0,12,1))
print(num_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [67]:
c=cl.Counter(num_list)

In [6]:
#create indexed lists through enumerate()
index_num_list = enumerate(num_list)
print(list(index_num_list))

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11)]


In [8]:
#apply function to each item in the list through map()
func_num_list = map(lambda x:x+1,num_list)
print(list(func_num_list))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [6]:
import numpy as np
np_array = np.array(num_list)

In [12]:
np_array.dtype

dtype('int64')

In [7]:
np_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [13]:
#operation on the array - broadcasting function
np_array_2 = np_array**2

In [14]:
np_array_2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [19]:
#new array through boolean indexing
np_array_3 = np_array[np_array > 5]

In [20]:
np_array_3

array([ 6,  7,  8,  9, 10, 11])

In [21]:
#array indexing and slicing
np_array[1:4]

array([1, 2, 3])

In [24]:
np_array[2:-1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#array iteration
for x in np_array:
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [27]:
np_array.shape

(12,)

In [43]:
#shape dimensions: 1D -> 2D
np_array_reshape=np_array.reshape(3,4)

In [44]:
np_array_reshape

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np_array_reshape.shape

(3, 4)

In [35]:
np_array_reshape[:-1]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
np_array_reshape[1:3]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [36]:
np_array_reshape[2,1]

9

In [48]:
#shape dimensions: 1D -> 3D
np_array_reshape=np_array.reshape(2,2,3)

In [38]:
np_array_reshape

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [39]:
np_array_reshape[:-1]

array([[[0, 1, 2],
        [3, 4, 5]]])

In [41]:
np_array_reshape[1,1]

array([ 9, 10, 11])

In [49]:
np_array_reshape[1,1,1]

10

In [50]:
np_array_reshape.ndim

3

In [53]:
np_array_nd = np.array([1,2],ndmin=3)

In [54]:
np_array_nd

array([[[1, 2]]])

In [25]:
num_array=map(lambda x:x+3,np_array)

In [26]:
np.array(list(num_array))

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
list(num_list2)

[3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

In [29]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %conda  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%